theme: jekyll-theme-cayman
google_analytics: UA-91426270-1
title_default: ISR Lab at Tsukuba
title_en: ISR Lab at Tsukuba
title_ja: 筑波大学ISR研究室
title_zh: 筑波大学ISR实验室
description_default: Research on Information Seeking and Retrieval at University of Tsukuba
description_en: Research and development on Information Seeking Behaviour and Information Retrieval
description_ja: 情報探索行動と情報検索の研究開発をしています
description_zh: 信息搜寻行为和信息检索的研究与开发
